### ISSUE TITLE
Memory Usage Exceptions

### ISSUE THREAD

**Issue by t2vee** [t2vee/mxs-avatar-service#1]
even on small vps instances or even light vms it will always through out of memory exceptions. It takes longer using smaller modules (obviously). Got to implement both minimum memory requirements in the readme and reduce tensorflows memory usage

**Comment by t2vee** [comment]
i forgot i already fixed this 😭😭
https://github.com/t2vee/nsfwjs-avatar-service/blob/main/lib/modelLoader.js#L5
https://github.com/t2vee/nsfwjs-avatar-service/blob/main/lib/modelLoader.js#L4
ill add the requirements to the readme though

**Comment by aubr3y-sh** [comment]
nice one
